CREATE TABLE Locations(
	ID INTEGER PRIMARY KEY NOT NULL,
	Timestamp TEXT NOT NULL,
	Latitude REAL NOT NULL,
	Longitude REAL NOT NULL
);

CREATE TABLE Status(
	ID INTEGER PRIMARY KEY NOT NULL,
	Timestamp TEXT NOT NULL,
	BatteryV REAL NOT NULL
);

CREATE TABLE Waypoints(
	ID INTEGER PRIMARY KEY NOT NULL,
	Latitude REAL NOT NULL,
	Longitude REAL NOT NULL
);
